"""add updated_at to companies

Revision ID: 7376646874d6
Revises: 4e8ec849f5a2
Create Date: 2026-05-13 12:28:26.586719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7376646874d6'
down_revision = '4e8ec849f5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('update_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
